# Generated by Django 3.1.1 on 2020-09-23 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0003_auto_20200922_1717'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-publication_date', '-id']},
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(default='not categorized', max_length=255),
        ),
    ]
