# Generated by Django 3.1.1 on 2020-09-28 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0006_auto_20200928_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='snippets',
            field=models.CharField(default='Click Link above to read blog post..', max_length=255),
        ),
    ]
